const usersData = [
  { name: 'stheabsoluta#5431', image: '/fotos/coroa.png' },
  { name: 'frigg#vitor' },
  { name: 'BREACHney spears#1181', image: '/fotos/girl.jpg' },
  { name: 'zBattisti#4709', image: '/fotos/girl.jpg' },
  { name: 'CamiTheCreator#7777', image: '/fotos/girl.jpg' },
  { name: 'Amaterasu#bibi', image: '/fotos/girl.jpg' },
  { name: 'began#5355', image: '/fotos/girl.jpg' },
  { name: 'way#aaaa', image: '/fotos/girl.jpg' },
  { name: 'maddu#8047', image: '/fotos/girl.jpg' },
  { name: 'vivi#bosta', image: '/fotos/girl.jpg' },
  { name: 'HTINHA#2004', image: '/fotos/girl.jpg' },
  { name: 'Japa 日本#2002', image: '/fotos/girl.jpg' },
  { name: 'CAQUI#marc', image: '/fotos/girl.jpg' },
  { name: 'Cyb3rGh0st#7840', image: '/fotos/girl.jpg' },
  { name: 'Peri Kitho#1798', image: '/fotos/girl.jpg' },
  { name: 'gabi risadinha#bosz', image: '/fotos/girl.jpg' },
  { name: 'madu#fps', image: '/fotos/girl.jpg' },
  { name: 'Indigri#indy', image: '/fotos/girl.jpg' },
  { name: 'fefelicis#4252', image: '/fotos/girl.jpg' },
  { name: 'Srta shark#3197', image: '/fotos/girl.jpg' },
  { name: 'ScarletEvans#OBR1', image: '/fotos/girl.jpg' },
  { name: 'LUNNARPsy#TTV', image: '/fotos/girl.jpg' },
  { name: 'mwa#bark', image: '/fotos/girl.jpg' },
  { name: 'Clara#TTV', image: '/fotos/girl.jpg' },
  { name: 'YunazX#1614', image: '/fotos/girl.jpg' },
  { name: 'kaaahpereirah#Cat', image: '/fotos/girl.jpg' },
  { name: 'Little Cat#kaah', image: '/fotos/girl.jpg' },
  { name: 'Macielitos#lelen', image: '/fotos/girl.jpg' },
  { name: 'Atena#1303', image: '/fotos/girl.jpg' },
  { name: 'Vênus#0006', image: '/fotos/girl.jpg' },
  { name: '10ContoACura#BR01', image: '/fotos/girl.jpg' },
  { name: 'Lulu#1492', image: '/fotos/girl.jpg' },
  { name: 'Bwguei#br1', image: '/fotos/girl.jpg' },
  { name: 'Ana#KILL', image: '/fotos/girl.jpg' },
  { name: 'Leonina#100', image: '/fotos/girl.jpg' },
  { name: 'Cervejinha#6122', image: '/fotos/girl.jpg' },
  { name: 'Cagix#9509', image: '/fotos/girl.jpg' },
  { name: 'Capybarazoka#BR1', image: '/fotos/girl.jpg' },
  { name: 'Manelinha#pinei', image: '/fotos/girl.jpg' },
  { name: 'July eilish#0022', image: '/fotos/girl.jpg' },
  { name: 'Maxú#Blue', image: '/fotos/girl.jpg' },
  { name: 'divine diegss#leon', image: '/fotos/girl.jpg' },
  { name: 'WandaSemCosmo#777', image: '/fotos/girl.jpg' }
];

export default usersData;
